# prometheus.yml

global:                          #This means Prometheus will scrape (collect) metrics every 15 seconds from all configured targets.
  scrape_interval: 15s
  
                                 # Prometheus needs to know what to monitor. Each job_name is a monitoring target.
scrape_configs:
  - job_name: "prometheus"
    static_configs:              # Prometheus monitors itself at localhost:9090.
      - targets: ["localhost:9090"]


                                 # Prometheus will scrape metrics from a node_exporter running on the server
                                 # Node Exporter gives CPU, RAM, disk, system stats.
  - job_name: "node_exporter"
    static_configs:
      - targets: ["server-IP:9100"]

  - job_name: "cadvisor"        # scrapes for cAdvisor, which provides Docker/container metrics.
    static_configs:
      - targets: ["server-IP:8088"]

  - job_name: "filebeat"
    static_configs:
      - targets: ["server-Ip:5044"]


